### ISSUE TITLE
Put required modules in the manifest

### ISSUE THREAD

**Issue by jdhitsolutions** [PoshlandPro/PSNotion#2]
If you plan to publish this module to the PowerShell Gallery, you can put your requirements for the secrets management modules in your module manifest.  Use the `RequiredModules` setting. Then, when someone installs your module from the PowerShell Gallery, the installation should also install your requirements.

**Comment by PoshlandPro** [comment]
@jdhitsolutions, that is a good point. I updated the manifest file.
